name:                h2048

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- random 
- split 

library:
  source-dirs: src

executables:
  h2048-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h2048
